### ISSUE TITLE
Update all QoS levels to guaranteed

### ISSUE THREAD

**Issue by jmorris-pillar** [smartcitiesdata/charts#126]
Our applications have defined their QoS levels (https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/) by happenstance and as such they do not necessarily align with our desires.  As a team we have decided to make all of our applications `Guaranteed` QoS

AC:
- All apps are running as guarneteed QoS in dev/staging/production.
- A test dataset is ran through staging to ensure the new requests/limits continue to properly allow dataset ingestion.

Amigos: 

@jmorris-pillar

**Comment by rob-h-m** [comment]
Include at the bottom of the board after refinement @rob-h-m

**Comment by NathanielScottStevens** [comment]
This article gave a helpful quick overview for me https://medium.com/google-cloud/quality-of-service-class-qos-in-kubernetes-bb76a89eb2c6
