### ISSUE TITLE
Create Mongo DB stateful set in kubernetes

### ISSUE THREAD

**Issue by rob-h-m** [smartcitiesdata/charts#131]
_As a data curator, I want to be able to ingest large datasets quickly so that they can provide value to the public with a quick turnaround._

### Acceptance Criteria
- [ ] Mongo db is available as a stateful set in kubernetes which maintains data across helm upgrades.
- [ ] The mongo db endpoint is only exposed inside the kubernetes cluster.
- [ ] 300GB SSD

**Comment by jeffgrunewald** [comment]
Going in a different direction.
