### ISSUE TITLE
Automatically back up MongoDB's EBS volume

### ISSUE THREAD

**Issue by rob-h-m** [smartcitiesdata/charts#132]
_As a data curator, I want to be able to ingest large datasets quickly so that they can provide value to the public with a quick turnaround._

### Acceptance Criteria
- [ ] Mongo's ebs is backed up daily.
- [ ] Backups are retained for 1 week.
- [ ] We successfully test the backup and restore process.

**Comment by jeffgrunewald** [comment]
Going in a different direction.
