### ISSUE TITLE
Create deployment chart for UDP push gateway

### ISSUE THREAD

**Issue by jeffgrunewald** [smartcitiesdata/charts#148]
#### User story
As a project,
I want the ability to deploy my new push gateway application
So that I can manage the application lifecycle

#### Acceptance criteria
- [x] Configurable push gateway chart
- [x] Creates deployment from configurable image and a service
- [x] Configurable names to allow for multiple push gateways to be deployed in parallel
- [x] Deployment repo consumes the chart and deploys the app

#### Tech Notes:
- Contains only our Docker image
#### Amigos:
@jeffgrunewald , @JarredOlson

**Comment by bbrewer-papa-x** [comment]
Pulling this in, as I'm j8s-less
